### ISSUE TITLE
Not working on Windows 11 Pro x64 version 10.0.22621

### ISSUE THREAD

**Issue by mohamed-khettab** [ms7m/notify-py#56]
upon running my code i get the following error:

Traceback (most recent call last):
  File "main.py", line 69, in <module>
    notifier = Notifier(api)
               ^^^^^^^^^^^^^
  File "main.py", line 54, in __init__
    self.notify()
  File "main.py", line 58, in notify
    notification = Notify(
                   ^^^^^^^
  File "C:\Users\khaoo\AppData\Local\Programs\Python\Python312\Lib\site-packages\notifypy\notify.py", line 69, in __init__
    self._notifier_detect = self._selected_notification_system()
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\khaoo\AppData\Local\Programs\Python\Python312\Lib\site-packages\notifypy\notify.py", line 123, in _selected_notification_system
    raise UnsupportedPlatform(
notifypy.exceptions.UnsupportedPlatform: This version of Windows (11) is not supported. is not supported.

**Comment by pekempy** [comment]
Also getting the same on 22631.2861

**Comment by mohamed-khettab** [comment]
Would be fixed by merging [#55](https://github.com/ms7m/notify-py/pull/55). Temporary fix [here.](https://github.com/ms7m/notify-py/pull/55#issuecomment-1913642269)
